<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 (Total recall) #

|  **Term**  |                                                       **Brief Description**                                                      |
|:----------:|:--------------------------------------------------------------------------------------------------------------------------------:|
| Subsetting | To select data from a list / array                                                                                               |
|  Indexing  | To select only one element from a list / array                                                                                   |
|   Slicing  | To select a range of elements from a list / array                                                                                |
|   Masking  | To select a range of elements that fulfil a set criterion from a list / array |

# Exercise 2 (Show me the 'odd' letters) #

In [1]:
import numpy as np

In [2]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d[:10,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [3]:
np_number_array = np_array_2d[:10,0]
np_array_int = np_number_array.astype(int)

In [10]:
np_array_int%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [4]:
np_array_odd = np_array_int%2
my_mask = np_array_odd == 1
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [5]:
np_array_2d[my_mask, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

# Exercise 3 #

In [1]:
import numpy as np

In [8]:
np_array = np.array([[66, 50, 57, -1, -1],
                    [92, -1, 88, -1, -1],
                    [75, -1, -1, 76, -1],
                    [-1, 51, 87, -1, -1],
                    [71, -1, 67, -1, 69]])

In [9]:
greater_mask = np_array > 50
equal_mask = np_array == 50
lesser_mask = np_array < 50

np_array[greater_mask] = 1
np_array[equal_mask] = 0
np_array[lesser_mask] = -1

np_array

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])