<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [2]:
import numpy as np

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [6]:
py_list[2]

'c3'

# 1 Subsetting: Indexing and Slicing

In [7]:
py_list[2:4]

['c3', 'd4']

In [8]:
py_list[2:5]

['c3', 'd4', 'e5']

In [12]:
py_list[5:2:-1]

['f6', 'e5', 'd4']

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

In [13]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = np_array > 3 
np_array[mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
np_array//2  # Quotient

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [18]:
np_array%2   # Remainder

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [19]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [20]:
np.logical_and(np_array > 3, np_array < 8)

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [23]:
py_list_2d[3][1]

'D'

In [24]:
np_array_2d[3,0]  # Only for Numpy

np.str_('4')

In [25]:
np_array_2d[:,1]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U21')

## 1.4 Growing lists

In [26]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

# Some loose ends

## 1.5 Tuples

In [ ]:
a = (1,2,3)
b =

In [27]:
a + [1]

NameError: name 'a' is not defined

## 1.6 Be VERY careful when copying

## Footnotes