<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [2]:
import numpy as np

## 1.1 Let’s compare

### Python Lists

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

### Numpy Arrays

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

### Dictionary

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [7]:
py_real_names[0]

'Natasha Romanoff'

In [17]:
i=0
print(py_real_names[i],' is ', py_super_names[i])

Natasha Romanoff  is  Black Widow


## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

In [18]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

## 1.4 Higher dimensional lists

In [19]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [21]:
py_superhero_info[0]

['Natasha Romanoff', 'Black Widow']

In [24]:
py_superhero_info[-1][-1]

'Doctor Strange'

# 2 Lists vs. Arrays

In [25]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [26]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [27]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

## 2.1 Size

In [28]:
len(py_list_2d)

10

In [29]:
len(np_array_2d)
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

## 2.3 Adding a number

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [31]:
py_list + 100

TypeError: can only concatenate list (not "int") to list

In [32]:
np_array + 100

array([101, 102, 103, 104, 105])

## 2.4 Adding another list

In [33]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [36]:
print(np_array_1, np_array_2, sep='\n')

[1 2 3 4 5]
[10 20 30 40 50]


In [37]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [38]:
py_list_2*2

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

## 2.5 Multiplying by a Number

## 2.6 Squaring

## 2.7 Asking questions

In [40]:
np_array == 3

array([False, False,  True, False, False])

In [41]:
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [46]:
min(py_list)

1

In [47]:
np_array.mean()

np.float64(3.0)

In [48]:
np_array.std()

np.float64(1.4142135623730951)

In [49]:
sum(py_list)/len(py_list)

3.0

In [50]:
np.median(np_array)

np.float64(3.0)

## Footnotes